### PR TITLE
Fix Android small Camera corner on Start. and old tool ?

### PR DESCRIPTION
**Pull request by namkazt**
artoolkit

1, Drop Texture and enter config to generate NFT
2, Drop fset,iset to view.

### CODE REVIEW

**Comment by namkazt** [comment]
Add Fixs for Android have small camera at corner when start app.
Add news functions : 
Open Camera 
Close Camera
Pause Camera
Resume Camera

**Comment by ThorstenBux** [comment]
Hi, why did you close this PR? Your work looks awesome and I'd like to review and merge it.

**Comment by namkazt** [comment]
sorry it seem no one look about it and it still have some problem cause app crash and i'm on fixing it.

**Comment by namkazt** [comment]
anyway for now need call OpenCamera separately from StartAR to avoid small camera at corner.

**Pull request closed without merging**
