### PR TITLE
Fix issue 132/135: Zero projection matrix returned on iOS IL2CPP with…

### PR DESCRIPTION
**Pull request by amechtley**
See e.g., https://github.com/artoolkit/arunity5/issues/132 and https://github.com/artoolkit/arunity5/issues/135

### CODE REVIEW

**Comment by amechtley** [comment]
It's possible some of the other methods in that file need similar fixes, but I've only fixed arwGetProjectionMatrix and arwQueryMarkerTransformation (and their stereo equivalents) since they're the only ones that relate to the tickets I noted in this PR.

**Comment by amechtley** [comment]
Yes I have verified this fixes the problem on the device. It results in different IL2CPP output. The important difference is that it will now generate something like the following output, right before the native function invocation (compare to the hack fix suggested by @namkazt in https://github.com/artoolkit/arunity5/issues/135):

```// Marshaling of parameter '___matrix0' to native representation
float* ____matrix0_marshaled = NULL;
if (___matrix0 != NULL)
{
	int32_t ____matrix0_Length = (___matrix0)->max_length;
	____matrix0_marshaled = il2cpp_codegen_marshal_allocate_array<float>(____matrix0_Length);
	for (int32_t i = 0; i < ____matrix0_Length; i++)
	{
		(____matrix0_marshaled)[i] = (___matrix0)->GetAtUnchecked(static_cast<il2cpp_array_size_t>(i));
	}
}
else
{
	____matrix0_marshaled = NULL;
}

**Comment by philip-lamb** [comment]
Nice work! I will do a couple of checks on the other native function signatures to make sure that there aren't any other stray arrays that need this fix, and then merge.

**Comment by BoiseBaked** [comment]
You probably want to leave off the [in] attribute on those parameters that are purely and only [out] parameters. Not that the marshaling semantics are difference, but just for readability.

**Comment by amechtley** [comment]
Agreed, and changed on the tip of my branch.

**Comment by amechtley** [comment]
Thanks! It's probably also a good idea to rebuild https://github.com/artoolkit/arunity5/blob/master/ARUnity5.unitypackage so that it contains the latest changes

**Comment by jose-ferrer** [comment]
I used this solution, but the 3d models are still not showing, any idea of why this might be?
This is the log from XCode:
`2017-05-22 12:18:05.593258-0600 LaNacionARS[11764:6710134] [DYMTLInitPlatform] platform initialization successful

2017-05-22 12:18:05.665398-0600 LaNacionARS[11764:6710023] -> registered mono modules 0x10113b9e0
2017-05-22 12:18:05.785951-0600 LaNacionARS[11764:6710023] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
-> applicationDidFinishLaunching()
2017-05-22 12:18:05.852942-0600 LaNacionARS[11764:6710023] Metal GPU Frame Capture Enabled
2017-05-22 12:18:05.853534-0600 LaNacionARS[11764:6710023] Metal API Validation Disabled
2017-05-22 12:18:05.909223-0600 LaNacionARS[11764:6710023] libMobileGestalt MobileGestaltSupport.m:153: pid 11764 (LaNacionARS) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
2017-05-22 12:18:05.909380-0600 LaNacionARS[11764:6710023] libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
-> applicationDidBecomeActive()
Renderer: Apple A10 GPU
Vendor:   Apple Inc.
Version:  OpenGL ES 2.0 Metal - 39.9
GLES:     2
GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_r
ead_format GL_IMG_texture_compression_pvrtc 
OPENGL LOG: Creating OpenGL ES 2.0 graphics device ; Context level  <OpenGL ES 2.0> ; Context handle 1946367648
Initialize engine version: 5.5.3f1 (4d2f809fd6f3)
-------- Shader compilation failed
#version 100
#extension GL_EXT_frag_depth : enable
precision highp float;
uniform highp vec4 _ProjectionParams;
uniform highp vec4 _ZBufferParams;
uniform highp mat4 unity_CameraToWorld;
uniform highp mat4 _NonJitteredVP;
uniform highp mat4 _PreviousVP;
uniform highp sampler2D _CameraDepthTexture;
varying highp vec2 xlv_TEXCOORD0;
varying highp vec3 xlv_TEXCOORD1;
void main ()
{
  highp vec4 tmpvar_1;
  tmpvar_1 = texture2D (_CameraDepthTexture, xlv_TEXCOORD0);
  mediump vec2 tmpvar_2;
  highp vec4 tmpvar_3;
  tmpvar_3.w = 1.0;
  tmpvar_3.xyz = ((xlv_TEXCOORD1 * (_ProjectionParams.z / xlv_TEXCOORD1.z)) * (1.0/((
    (_ZBufferParams.x * tmpvar_1.x)
   + _ZBufferParams.y))));
  highp vec4 tmpvar_4;
  tmpvar_4 = (unity_CameraToWorld * tmpvar_3);
  highp vec4 tmpvar_5;
  tmpvar_5 = (_PreviousVP * tmpvar_4);
  highp vec4 tmpvar_6;
  tmpvar_6 = (_NonJitteredVP * tmpvar_4);
  highp vec2 tmpvar_7;
  tmpvar_7 = (((tmpvar_5.xy / tmpvar_5.w) + 1.0) / 2.0);

  highp vec2 tmpvar_8;
  tmpvar_8 = (((tmpvar_6.xy / tmpvar_6.w) + 1.0) / 2.0);
  tmpvar_2 = (tmpvar_8 - tmpvar_7);
  mediump vec4 tmpvar_9;
  tmpvar_9.zw = vec2(0.0, 1.0);
  tmpvar_9.xy = tmpvar_2;
  gl_FragDepthEXT = tmpvar_1.x;
  gl_FragData[0] = tmpvar_9;
}
-------- failed compiling:
fragment evaluation shader
WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported
ERROR: 0:38: Use of undeclared identifier 'gl_FragDepthEXT'

Note: Creation of internal variant of shader 'Hidden/Internal-MotionVectors' failed.
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Setting to default shader.
UnloadTime: 9.435458 ms
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 1.643500 ms

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 286.
Total: 0.452541 ms (FindLiveObjects: 0.023083 ms CreateObjectMapping: 0.011166 ms MarkObjects: 0.261833 ms  DeleteObjects: 0.156000 ms)

Unloading 3 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.575166 ms

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 329.
Total: 0.725750 ms (FindLiveObjects: 0.021458 ms CreateObjectMapping: 0.007375 ms MarkObjects: 0.194083 ms  DeleteObjects: 0.502416 ms)

The referenced script on this Behaviour (Game Object 'Nombre 3') is missing!
 
(Filename:  Line: 1754)

The referenced script on this Behaviour (Game Object 'Nombre 4') is missing!
 
(Filename:  Line: 1754)

The referenced script on this Behaviour (Game Object 'Nombre 2') is missing!
 
(Filename:  Line: 1754)

The referenced script on this Behaviour (Game Object 'Nombre 5') is missing!
 
(Filename:  Line: 1754)

The referenced script on this Behaviour (Game Object 'Nombre 7') is missing!
 
(Filename:  Line: 1754)

The referenced script on this Behaviour (Game Object 'Nombre') is missing!
 
(Filename:  Line: 1754)

The referenced script on this Behaviour (Game Object 'Nombre 6') is missing!
 
(Filename:  Line: 1754)

The referenced script on this Behaviour (Game Object 'Nombre 8') is missing!
 
(Filename:  Line: 1754)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 1.043250 ms
Default clip could not be found in attached animations list.
 
(Filename:  Line: 403)

The AnimationClip 'C4D Animation Take' used by the Animation component 'LowPolyThrushFinalAnim' must be marked as Legacy.
 
(Filename:  Line: 2019)

Default clip could not be found in attached animations list.
 
(Filename:  Line: 403)

The AnimationClip 'C4D Animation Take' used by the Animation component 'LowPolyThrushFinalAnim' must be marked as Legacy.
 
(Filename:  Line: 2019)

Default clip could not be found in attached animations list.
 
(Filename:  Line: 403)

The AnimationClip 'C4D Animation Take' used by the Animation component 'LowPolyThrushFinalAnim' must be marked as Legacy.
 
(Filename:  Line: 2019)

Default clip could not be found in attached animations list.
 
(Filename:  Line: 403)

Default clip could not be found in attached animations list.
 
(Filename:  Line: 403)

The AnimationClip 'C4D Animation Take' used by the Animation component 'LowPolyThrushFinalAnim' must be marked as Legacy.
 
(Filename:  Line: 2019)

Default clip could not be found in attached animations list.
 
(Filename:  Line: 403)

The AnimationClip 'C4D Animation Take' used by the Animation component 'LowPolyThrushFinalAnim' must be marked as Legacy.
 
(Filename:  Line: 2019)

Default clip could not be found in attached animations list.
 
(Filename:  Line: 403)

The AnimationClip 'C4D Animation Take' used by the Animation component 'LowPolyThrushFinalAnim' must be marked as Legacy.
 
(Filename:  Line: 2019)

Default clip could not be found in attached animations list.
 
(Filename:  Line: 403)

2017-05-22 12:18:16.375087-0600 LaNacionARS[11764:6710023] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-05-22 12:18:16.376094-0600 LaNacionARS[11764:6710023] [MC] Reading from public effective user settings.
ARController (native): [info]ARWrapper::ARController::initialiseBase(): Initialising...
ARController: ARToolKit version 5.3.2 initialised.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:InitializeAR()
ARController:Awake()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: PluginFunctions initialized: True
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:OnEnable()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController (native): [info]Loading single AR marker from buffer, width 80.000000.
ARController (native): [info]Added marker (UID=0), total markers loaded: 1.
ARController (native): [info]Loading single AR marker from buffer, width 80.000000.
ARController (native): [info]Added marker (UID=1), total markers loaded: 2.
ARController (native): [info]Loading single AR marker from buffer, width 80.000000.
ARController (native): [info]Added marker (UID=2), total markers loaded: 3.
ARController (native): [info]Loading single AR marker from buffer, width 80.000000.
ARController (native): [info]Added marker (UID=3), total markers loaded: 4.
ARController (native): [info]Loading single AR marker from buffer, width 80.000000.
ARController (native): [info]Added marker (UID=4), total markers loaded: 5.
ARController (native): [info]Loading single AR marker from buffer, width 80.000000.
ARController (native): [info]Added marker (UID=5), total markers loaded: 6.
ARController (native): [info]Loading single AR marker from buffer, width 80.000000.
ARController (native): [info]Added marker (UID=6), total markers loaded: 7.
ARController (native): [info]Loading single AR marker from buffer, width 80.000000.
ARController (native): [info]Added marker (UID=7), total markers loaded: 8.

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 616.
Total: 5.745750 ms (FindLiveObjects: 0.134708 ms CreateObjectMapping: 0.049291 ms MarkObjects: 0.909708 ms  DeleteObjects: 4.651166 ms)

ARController: Starting AR.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:StartAR()
ARController:Start()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Render device: OpenGL ES 2.0 Metal - 39.9, using Unity texturing.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:StartAR()
ARController:Start()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Starting ARToolKit video with vconf ' -format=BGRA'.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:StartAR()
ARController:Start()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController (native): [info]ARController::startRunning(): called, start running
ARController (native): [info]Setting video configuration ' -format=BGRA'.
ARController (native): [info]Opening ARToolKit video using configuration ' -format=BGRA'.
Using supplied video config " -format=BGRA".
Requesting images in BGRA format.
ARController: Setting ARToolKit tracking settings.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:StartAR()
ARController:Start()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

AROrigin: Found 8 markers eligible to become base marker.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
AROrigin:FindMarkers()
AROrigin:Start()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: UpdateAR: Waiting for ARToolKit video.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:UpdateAR()
ARController:Update()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController (native): [info]Opened ARToolKit video 480x360@4Bpp (AR_PIXEL_FORMAT_BGRA).
Unable to find suitable camera parameters for device iPhone (Unknown model).
ARController (native): [info]Fetching external camera parameters.
cparamSearch beginning search for apple/iPhone/iPhone9,3, camera 0, aspect ratio 4:3.
ARController (native): [warning]Using default camera parameters for 480x360 image size, 45 degrees vertical field-of-view.
ARController: UpdateAR: ARToolKit video is running. Configuring Unity scene for video.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:UpdateAR()
ARController:Update()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Video 480x360@4Bpp (AR_PIXEL_FORMAT_BGRA)
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:UpdateAR()
ARController:Update()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Projection matrix: [
0.00000	0.00000	0.00000	0.00000
0.00000	0.00000	0.00000	0.00000
0.00000	0.00000	0.00000	0.00000
0.00000	0.00000	0.00000	0.00000]
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:UpdateAR()
ARController:Update()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Video size 480x360 will use texture size 480x360.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:CreateVideoBackgroundMesh(Int32, Int32, Int32, Int32, Color[]&, Color32[]&, Texture2D&, Material&)
ARController:UpdateAR()
ARController:Update()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Scene configured for video.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Debug:LogException(Exception)
UnityEngine.Logger:Log(LogType, Object)
System.Collections.ObjectModel.Collection`1:Remove(T)
UnityEngine.Debug:Log(Object)
ARController:Log(String)
ARController:UpdateAR()
ARController:Update()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

arVideoLuma will use ARM NEON acceleration.
ARController (native): [info]ARController::initAR() called
ARController (native): [info]Marker 6 now visible
ARController (native): [info]Marker 6 no longer visible
ARController (native): [info]Marker 6 now visible
ARController (native): [info]Marker 6 no longer visible
`
I really need help, I'm on a deadline and I have tried everything I can think of. 
Thanks in advance.

**Comment by BoiseBaked** [comment]
@jose-ferrer

As stated here by @amechtley on Feb 7
"Thanks! It's probably also a good idea to rebuild https://github.com/artoolkit/arunity5/blob/master/ARUnity5.unitypackage so that it contains the latest changes"

This probably hadn't been done yet. So what you have to do is pull down (using git) the latest and greatest, from the master branch, source of artoolkit/arunity5.

Look in specifically:
arunity5/src/Unity/Assets/ARToolKit5-Unity/Scripts/ARNativePluginStatic.cs

Find the following text:
public static extern bool arwQueryMarkerTransformation(int markerID, [Out][MarshalAs(UnmanagedType.LPArray, SizeConst=16)] float[] matrix);

and make sure there is a [Out] parameter attribute in front of the matrix array parameter.

That was the fix for what is being discussed in this thread. I like I stated above the fix was probably not rolled into the SDK as of yet. So go to the source, the git repo and build your app using that source.

JohnW

**Comment by jose-ferrer** [comment]
@BoiseBaked 
That was exactly the issue, it does work now! Thanks!

**Pull request merged**
