### PR TITLE
Upgraded project for Unity 5.1.1. Reorganised plugin assets within the Assets folder. Set plugin import settings to be platform specific.

### PR DESCRIPTION
**Pull request by r0bbie**
Three main changes included:

- Upgraded the project to Unity 5.1.1.
(see - https://github.com/artoolkit/arunity5/commit/d8e03eb8f1f25ff51bb509fa19f609c7c4b4a903)

- Reorganised plugin assets within the Assets folder to resemble a more self-contained package
which could be imported into an existing Unity project in a tidy manner.
(see - https://github.com/artoolkit/arunity5/commit/eb6b53cc3fbb1b61277c271a47e5aa78cf24f5fa)

- Set plugin import settings to be platform specific. This is a key update which allows the package to be imported into either the Windows or Mac Editor and be used across platforms without the need to remove some of the plugin folders.
(see - https://github.com/artoolkit/arunity5/commit/03108859a42bfdfe66a4478318cf4d81b520fa48)

### CODE REVIEW

**Comment by wallywyyoung** [comment]
Hey r0bbie, thanks for this.

Working on reviewing now.

I'd like you to keep in mind that currently this package works "as-is" with Unity 4.x:

* There were many API changes in Unity 5.x, but the GetComponent<> change should work in 4.x as well.

* I'd be hesitant to make changes like reorganizing the plugins folder because Unity 5 now allows it, when Unity 4 does not, and would work either way.

* Unity 4 I believe still used "iPhone" (which always drove me crazy), and not "iOS".

**Comment by r0bbie** [comment]
Hey wallywyyoung,

That’s great - hopefully the contributions are found useful! In terms of the Unity 4.x backwards compatibility - I misinterpreted artoolkit5 to be ARToolkit for Unity 5, rather than ARToolkit 5 for Unity, and missed the backwards compatibility line in the readme. Apologies!

I've added some version dependent compilation #ifs around the offending code in latest commit that should ensure the Unity 5 changes don’t impact on backwards compatibility with 4.5.5+.

In terms of the Plugins folder: While I would suggest it might be a good idea re-organising the ARToolkit related assets overall to be more self-contained in order to allow for easy importing into existing projects in a tidy manner (as in commit https://github.com/r0bbie/arunity5/commit/eb6b53cc3fbb1b61277c271a47e5aa78cf24f5fa) I deliberately didn’t touch the Plugins folder itself. I think there potentially is an argument that could be made for maintaining that convention in Unity 5, even though it no longer requires it. This does also mean the proposed folder structure should also be fully compatible with both Unity 4.x and 5.x. :)

**Comment by wallywyyoung** [comment]
Thank you @r0bbie! I'm traveling now, but will be back en-force tomorrow. I can't wait to test this out!

RE: Plugins folder. I totally understand. Encapsulation (especially in a library or subproject) is a good thing. I'd hate to contaminate a larger project and have no idea where what is what, were I the unfortunate dev.

**Comment by wallywyyoung** [comment]
Thank you @r0bbie for your contribution!

**Pull request merged**
